build: List go:generate tools in tools.go
syncthing/syncthing pull request #7599
Opened 2021-04-25 12:44 UTC by greatroar

This reuses [conventional go build machinery](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module) to simplify build.go, as suggested by @imsodin at #7552. `go generate` just works, without having genxdr or counterfeiter installed. `go mod tidy` no longer removes counterfeiter.

There's more work to be done on this front, in particular wrt. protobufs, but I figured I'd send a PR to test the waters and see if you want to move in this direction at all.

2021-04-25 13:44 UTC, calmh commented
Sounds good 👍

2021-04-25 15:59 UTC, AudriusButkevicius approved these changes
lgtm

2021-04-25 17:20 UTC, imsodin requested changes
Why is the `github.com/gogo/protobuf` repo still needed - it's also part of the new tools.go and thus should be provided like that, shouldn't it?

2021-04-25 21:41 UTC, greatroar commented
Protobufs takes more work due to the need to import a protobuf file from the gogo/protobuf repo. I'll leave the PR at this for now.

2021-04-25 21:48 UTC, greatroar commented
Oh and the protoc compiler (which has to still be installed separately) needs to invoke the protoc-gen-gogo command, so that has to be compiled and in its PATH.

2021-04-26 08:18 UTC, imsodin approved these changes
Thanks for the explanation, lgtm too.

2021-04-26 17:18 UTC, greatroar commented
Rebased on main. By the way, you may want to re-run `build.go proto` and check in the result. It changes two imports on main.

2021-05-08 07:29 UTC, greatroar commented
Rebased again.

2021-05-08 10:51 UTC, imsodin approved these changes

2021-05-08 10:52 UTC, merged