cmd/syncthing: Work around binary in current dir restriction (fixes #8499)
syncthing/syncthing pull request #8500
Opened 2022-08-13 15:42 UTC by imsodin

Apparently there's an `exec.ErrDot` error handling this case and it should return the local path in that case, however I did not get that behaviour playing around with it (`exec.LookupPath("test.sh")` returned `ErrNotFound`).  So I just "manually" handled it regardless of what the error is.

2022-08-13 15:52 UTC, tomasz1986 commented
Perfect 🙂. Just tested, and everything seems to work as expected.

2022-08-13 17:52 UTC, calmh requested changes
IMHO this should be scoped to windows only and perhaps look specifically in the directory the executable lives in rather than dot...

2022-08-14 13:22 UTC, imsodin commented
Changed it to be windows only (hoping no-one will find a way to run a local binary on unixes without the `./` prefix :) ).

Not sure what you mean with the directory/dot: This restriction is specifically about the binary being in the current directory/dot, and not being a path. Checking in `$PWD/<binary>` and `./<binary>` should be equivalent, right?

2022-08-14 14:13 UTC, calmh commented
Yeah I guess what I meant is that in the general case we're interests in running the same binary as the monitor. There's a library call to get the directory of the currently running binary. That's probably where we should look, and whether dot is in the path or the binary is in $PWD then doesn't really matter?

2022-08-14 14:44 UTC, calmh approved these changes
LGTM. Looking at this from a higher level it seems to me we should always use os.Executable and only resort to a PATH search if that's unavailable for some reason... but that's a behaviour change and this is a bug fix 🤷

2022-08-14 19:25 UTC, merged