Updated script to download Transifex translations
syncthing/syncthing pull request #8713
Opened 2022-12-11 19:09 UTC by calmh

Throw away our old API integration and use the `tx` CLI, via a docker container.

2022-12-11 19:39 UTC, acolomb commented
No time to review anymore today, but will try to get to it tomorrow.

2022-12-12 11:51 UTC, acolomb commented
Are you planning to reimplement the `prettyprint.js` and `valid-langs.js` stuff again?

With Weblate, I was going to stick closely to what the old script did, which is rather easy with their API. The main difference will be that we should keep all translations (whether valid or not) in our Git repo, as Weblate basically uses Git as its storage and preferably everything is synced with upstream. So filtering should still happen through the `valid-langs.js` file, regardless of how many JSON translations are sitting around.

What reasoning do we have for rewriting underscores to hyphens in the language codes? With both solutions, just keeping the underscore would be easier, no?

2022-12-12 12:44 UTC, calmh commented
Right, those still need generating... The reason for dashes is that it's what's expected by the GUI framework, afaik.

2022-12-16 20:29 UTC, acolomb requested changes

2022-12-16 20:29 UTC, acolomb commented on script/transifexdl.sh
> +for f in *_* ; do
```suggestion
for f in lang-*_*.json ; do
```

2023-02-09 08:15 UTC, calmh commented
Now irrelevant

2023-02-09 08:15 UTC, closed without merging