Correct various typos
syncthing/syncthing pull request #8870
Opened 2023-04-12 03:05 UTC by goggle

### Purpose
Corrects some typos that I've found in the repository.

2023-04-12 05:01 UTC, calmh commented
Half of this is in autogenerated files. If you avoid those, the rest makes sense.

2023-04-12 19:32 UTC, acolomb approved these changes
Looks good in code, but I haven't tested it or checked whether all instances of the variable renames were caught.

2023-04-13 07:43 UTC, calmh commented on man/syncthing-rest-api.7
> -Summarizes the completion precentage for each remote device.  Returns an object
This file is autogenerated from the docs repo

2023-04-13 07:44 UTC, calmh requested changes
(Remove changes to autogenerated files)

2023-05-09 06:52 UTC, calmh approved these changes

2023-05-09 06:54 UTC, merged