lib/config, lib/model: Better error message for insufficient space
syncthing/syncthing pull request #8992
Opened 2023-07-19 20:23 UTC by calmh

By not using a colon, the error doesn't get prematurely cut off in the GUI.

<img width="920" alt="Screenshot 2023-07-19 at 22 23 00" src="https://github.com/syncthing/syncthing/assets/125426/00f0b57d-0f64-4d55-b145-449a99cf8bac">

2023-07-24 09:32 UTC, imsodin commented on lib/config/folderconfiguration.go
> +		return fmt.Errorf("insufficient space in folder %v (%v) - %w", f.Description(), fs.URI(), err)
Feels wrong to change (a common) pattern in error formatting to work around a UI issue - couldn't we teach the UI to not hide stuff after/before a colon (or whatever it does)?

2023-07-26 06:45 UTC, calmh commented on lib/config/folderconfiguration.go
> +		return fmt.Errorf("insufficient space in folder %v (%v) - %w", f.Description(), fs.URI(), err)
Of course, but we do that for a reason, as the full error is often quite long and hides the most important part at the end.

2023-07-26 10:41 UTC, AudriusButkevicius commented on lib/config/folderconfiguration.go
> +		return fmt.Errorf("insufficient space in folder %v (%v) - %w", f.Description(), fs.URI(), err)
`sed s#:#<br/>#g` in the ui?

2023-07-26 21:13 UTC, imsodin commented on lib/config/folderconfiguration.go
> +		return fmt.Errorf("insufficient space in folder %v (%v) - %w", f.Description(), fs.URI(), err)
Then the 5+ times wrapped error will create ugly, super high table cells. 

Yeah forgot about that - not a particularly good solution to that problem (too long errors), but I am pretty inclined to go ¯\_ (ツ)_/¯ - this does solve this particular issue with minimal effort.

2023-07-26 21:14 UTC, imsodin approved these changes

2023-07-26 21:15 UTC, imsodin requested changes
Oh never mind, there's https://github.com/syncthing/syncthing/pull/9005/files

2023-07-26 21:20 UTC, closed without merging